name: production

on:
  push:
    branches: [ Production ]
  pull_request:
    branches: [ Production ]

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/server/prod/02363-frontend/

    steps:
    - uses: actions/checkout@v2
    - name: Pull from Github
      run: sudo git pull

    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo yarn

    - uses: actions/checkout@v2
    - name: Build application
      run: sudo yarn build

    - uses: actions/checkout@v2
    - name: Copy to Nginx
      run: sudo cp -a build/. /usr/share/nginx/html/